apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: springapp
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springbootdep
  name: springbootdep
  namespace: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springbootdep
    spec:
      containers:
      - image: bhuvnesh94/springboot_hello:latest
        name: springboothelloapp
        resources: {}
        imagePullPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springbootsvc
  name: springbootsvc
  namespace: springapp
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootdep
  type: NodePort
status:
  loadBalancer: {}
